In [1]:
import numpy as np

In [49]:
a = np.arange(11, 36).reshape(5, 5)

print(a[0, 1:-1])

print(a[1:-1, 0])

print(a[::2, ::2])

print(a[:, 1])



[12 13 14]
[16 21 26]
[[11 13 15]
 [21 23 25]
 [31 33 35]]
[12 17 22 27 32]
